#!/usr/bin/env python
# -*- encoding: utf-8 -*-
# Copyright (c) 2013 Hannes Körber <hannes.koerber+rbackupd@gmail.com>

import sys

import rbackupd.daemon

if __name__ == "__main__":
    rbackupd.daemon.main(sys.argv[1:])
