#!/usr/bin/env python

import sys

import rbackupd

def main():
    if len(sys.argv) != 2:
        print("Invalid arguments.")
        sys.exit(1)
    rbackupd.run(sys.argv[1])

if __name__ == "__main__":
    main()
