#!/usr/bin/env python
# -*- encoding: utf-8 -*-
# Copyright (c) 2014 Hannes Körber <hannes.koerber+rbackupd@gmail.com>

import sys

import rbackupc.client

if __name__ == "__main__":
    rbackupc.client.main(sys.argv[1:])
